services:
  - type: web
    name: securevault
    runtime: node
    plan: free

    buildCommand: >
      cd client && npm ci --include=dev && npm run build && cd ../server && npm ci --omit=dev

    startCommand: "cd server && node db/seed.js && node server.js"

    healthCheckPath: /api/health

    envVars:
      - key: NODE_VERSION
        value: "20.18.0"

      - key: NODE_ENV
        value: "production"

      - key: LAB_MODE
        value: "true"

      - key: DB_PATH
        value: "/tmp/vault.db"

      - key: BCRYPT_ROUNDS
        value: "10"

      - key: COOKIE_SECURE
        value: "true"

      - key: ENCRYPTION_KEY
        sync: false

      - key: JWT_SECRET
        sync: false
